#' Estimate motif-specific on-target mutation rates using prior probability
#'
#' \code{estimate_inference_with_prior} performs motif-aware inference using motif prior probabilities, and estimates site-level mutation or conversion signal along with posterior probabilities.
#'
#' @param chr.info A \code{data.frame} with three columns: site position in the format "chrom_coordinate_strand" (e.g., chr1_14404_-), site motif sequence (e.g., AAACC), and site motif type (e.g., NNUNN).
#' @param treatment_fixed_count A \code{vector} of non-mutation counts for each site in the treatment sample.
#' @param control_fixed_count A \code{vector} of non-mutation counts for each site in the control sample.
#' @param treatment_depth A \code{vector} of read coverage for each site in the treatment sample.
#' @param control_depth A \code{vector} of read coverage for each site in the control sample.
#' @param motif_specific Logical. Whether to estimate on-target mutation rates by motif. If \code{FALSE}, one overall mutation rate is estimated. Default is \code{TRUE}.
#' @param delta The sequencing error rate. Default is 0.001.
#' @param depth.cutoff The minimum read coverage for each site in the treatment and control sample. Default is 10.
#' @param homo.cutoff The minimum ratio of non-mutation counts for each site in the control sample that is used to determine homozygous sites. Default is 0.99.
#' @param bg.method The statistical test to infer the background sites. One of "binomial", "fisher", "lrt". Default is "fisher".
#' @param highly.methyl.cutoff The upper quantile cutoff of candidate signal sites used for estimating on-target mutation rates. This argument name is retained for backward compatibility. Default is 0.95.
#' @param ref.freq.tab A \code{data.frame} with motif frequencies in signal and background sets, plus the prior probability of each motif sequence. This table can be created by \code{\link{compute_prior}} and must contain the columns "motif" and "prior_methylated".
#' @param seed A seed for the random number generators.
#' @param thread A positive integer numeric specifying the number of cores for parallel computing. Default is 1.
#' @param motif The target 5-mer motif pattern. MIRAGE expands supported degenerate bases internally. The default is "DRACH"; set this explicitly for the assay being analyzed.
#' @param Nmer The strategy for further grouping motifs. One of "5mer", "f4mer" or "l4mer". "5mer" will not consider further grouping strategy. In the "f4mer" and "l4mer" mode, all 5-mer motifs are grouped by sharing the same first or last 4-mer sequences, respectively. The argument is only used if \code{motif_specific = TRUE}.
#'
#' @return A \code{list} including a \code{data.frame} of homozygous sites, a \code{data.frame} of heterozygous sites, a \code{data.frame} of estimated on-target mutation rates for each motif (lambda1), and the estimated background mutation rate (lambda2).
#'
#' @details \code{estimate_inference_with_prior} estimates site-level signal from motif prior probabilities, which are usually obtained by \code{\link{compute_prior}}.
#' The count table can be generated by any preprocessing pipeline as long as it contains site IDs, motif annotations, treatment and control fixed-base counts, and treatment and control read depths in the expected order.
#'
#' @examples
#' # Estimate signal levels from a PAR-CLIP count table with motif priors.
#' count_table <- read.delim(system.file("extdata", "pos.read.count.example.parclip.txt",
#'                                       package = "MIRAGE"))
#'
#' motif_counts <- table(count_table$motif)
#' motif_freq_exp <- data.frame(motif = names(motif_counts),
#'                              freq = as.numeric(motif_counts) / sum(motif_counts))
#' motif_freq_bg <- data.frame(motif = names(motif_counts),
#'                             tx_count = as.numeric(motif_counts),
#'                             genome_count = as.numeric(motif_counts))
#' motif_prior <- compute_prior(motif_freq_exp, motif_freq_bg, target_motif = "NNUNN",
#'                              target_base_index = 3, prob_methylation = 0.01)
#'
#' res <- with(count_table, estimate_inference_with_prior(cbind(pos, motif, type),
#'             treated_fixed_count, control_fixed_count, treated_depth, control_depth,
#'             motif_specific = FALSE, delta = 0.001, depth.cutoff = 10,
#'             highly.methyl.cutoff = 0.95, ref.freq.tab = motif_prior,
#'             seed = 123, thread = 1, motif = "NNUNN", Nmer = "5mer"))
#' head(res$homosites[, c("pos", "motif", "beta_est", "posterior")])
#'
#' @export

estimate_inference_with_prior <- function(chr.info, treatment_fixed_count, control_fixed_count, treatment_depth, control_depth, motif_specific = TRUE, delta = 0.001, depth.cutoff = 10, homo.cutoff = 0.99, bg.method = "fisher", highly.methyl.cutoff = 0.95, ref.freq.tab = NULL, seed = NULL, thread = 1, motif = "DRACH", Nmer = "5mer"){



  treatment_fixed_rate <- treatment_fixed_count/treatment_depth
  control_fixed_rate <- control_fixed_count/control_depth

  treatment_X_rate <- 1 - treatment_fixed_rate
  control_X_rate <- 1 - control_fixed_rate

  allsites <- data.frame(chr.info,  treatment_X_rate, control_X_rate, treatment_fixed_rate, control_fixed_rate, treatment_fixed_count, control_fixed_count, treatment_depth, control_depth)
  allsites <- allsites[allsites$treatment_depth >= depth.cutoff & allsites$control_depth >= depth.cutoff, ]

  ####### Select homozygous sites based on the AF #######
  homo.ID <- which(allsites$control_fixed_rate > homo.cutoff)
  homosites <- allsites[homo.ID, ]
  homosites_percentage <- round(nrow(homosites)/nrow(allsites)*100,2)
  cat(paste0("Considering ",nrow(homosites)," (",homosites_percentage,"%) sites as homozygous...\n"))
  background.cutoff <- quantile(homosites$treatment_X_rate, 0.95)
  initial_background_rate <- median(homosites$treatment_X_rate[homosites$treatment_X_rate <= background.cutoff])

  if(thread == 1) {
    homosites.initial.test.summary <- test_for_mutation_given_a_rate(homosites$treatment_fixed_count, homosites$treatment_depth, homosites$control_fixed_count, homosites$control_depth, initial_background_rate)
  } else {
    cl <- makeCluster(thread, type="FORK")
    registerDoParallel(cl)
    cat(paste("Hyper-thread registered:",getDoParRegistered(),"\n"))
    cat(paste("Using",getDoParWorkers(),"threads to make homo initial test...\n"))
    homosites_treatment_fixed_count_split <- split(homosites$treatment_fixed_count, factor(sort(1:length(homosites$treatment_fixed_count)%%thread)))
    homosites_treatment_depth_split <- split(homosites$treatment_depth, factor(sort(1:length(homosites$treatment_depth)%%thread)))
    homosites_control_fixed_count_split <- split(homosites$control_fixed_count, factor(sort(1:length(homosites$control_fixed_count)%%thread)))
    homosites_control_depth_split <- split(homosites$control_depth, factor(sort(1:length(homosites$control_depth)%%thread)))
    homosites.initial.test.summary <- foreach(i = 1:thread, .combine = rbind) %dopar% {
      test_for_mutation_given_a_rate(as.vector(unlist(homosites_treatment_fixed_count_split[i])), as.vector(unlist(homosites_treatment_depth_split[i])), as.vector(unlist(homosites_control_fixed_count_split[i])), as.vector(unlist(homosites_control_depth_split[i])), initial_background_rate)
    }
    stopCluster(cl)
  }

  ####### Estimate mutation rate in background #######
  if(bg.method == "binomial") {
    Igroup0 <- which(homosites.initial.test.summary$binom_p > 0.05)
    Igroup1 <- which(homosites.initial.test.summary$binom_fdr < 0.05)
  } else if(bg.method == "fisher") {
    Igroup0 <- which(homosites.initial.test.summary$fisher_p > 0.05)
    Igroup1 <- which(homosites.initial.test.summary$fisher_fdr < 0.05)
  } else if(bg.method == "lrt") {
    Igroup0 <- which(homosites.initial.test.summary$lrt_p > 0.05)
    Igroup1 <- which(homosites.initial.test.summary$lrt_fdr < 0.05)
  } else {
    cat("The bg.method option is only one of binomial, fisher or lrt!!!\n")
    q(status = 1)
  }
  #Igroup0 <- which(homosites.initial.test.summary$binom_p > 0.05)
  candidate.background.sites <- homosites[Igroup0, ]
  candidate.background.sites.percentage <- round(nrow(candidate.background.sites)/nrow(homosites)*100,2)
  cat(paste0("Considering ",nrow(candidate.background.sites)," (",candidate.background.sites.percentage,"%) sites as background (homozygous sites only)...\n"))
  N_fixed_treatment <- candidate.background.sites$treatment_fixed_count
  N_total_treatment <- candidate.background.sites$treatment_depth

  lambda2.est <- MLE_for_lambda2(N_fixed_treatment, N_total_treatment, num.sites = 100000, delta = delta, initial_lambda2 = 0.1, seed = seed)

  #homosites.initial.test.summary_with_estimated_lambda2 <- test_for_mutation_given_a_rate(homosites$treatment_fixed_count, homosites$treatment_depth, lambda2.est)

  ####### Estimate mutation rate in high-signal sites #######
  #Igroup1 <- which(homosites.initial.test.summary[, 1]<=0.05)
  #Igroup1 <- which(homosites.initial.test.summary$fisher_fdr < 0.05)
  candidate.highly.methylated.sites <- homosites[Igroup1, ]
  candidate.highly.methylated.sites.percentage <- round(nrow(candidate.highly.methylated.sites)/nrow(homosites)*100,2)
  cat(paste0("Considering ",nrow(candidate.highly.methylated.sites)," (",candidate.highly.methylated.sites.percentage,"%) sites as high-signal site candidates (homozygous sites only)...\n"))
  high.cutoff <- quantile(candidate.highly.methylated.sites$treatment_X_rate, highly.methyl.cutoff)
  candidate.highly.methylated.sites.filter <- candidate.highly.methylated.sites[candidate.highly.methylated.sites$treatment_X_rate>=high.cutoff, ]

  N_fixed_treatment_prime <- candidate.highly.methylated.sites.filter$treatment_fixed_count
  N_total_treatment_prime <- candidate.highly.methylated.sites.filter$treatment_depth
  lambda1.est <- MLE_for_lambda1(N_fixed_treatment_prime, N_total_treatment_prime, delta = delta, initial_lambda1 = 0.2)

  target_motif <- generate_motif_sequences(motif)
  #target_motif <- data.frame(D = rep(c("G", "A", "U")), R = rep(c("G", "A"), each = 9), AC = rep("AC", 18), H = rep(rep(c("A", "C", "U"), each = 3), 2))
  motif_seqs <- apply(target_motif, 1, function(x){paste(x, collapse = "")})
  motif_ref <- toupper(chr.info[, 2])
  motif_ref_types <- unique(motif_ref)


  if(motif_specific == TRUE) {

    ####### Estimate mutation rate in high-signal sites for each target motif #######
    lambda1.motif_seqs.est <- rep(NA, length(motif_seqs))
    if(Nmer == "5mer") {
      for(i in 1:length(motif_seqs)){
          candidate.highly.methylated.sites.motif <- candidate.highly.methylated.sites[candidate.highly.methylated.sites$motif %in% motif_seqs[i], ]
          high.cutoff <- quantile(candidate.highly.methylated.sites.motif$treatment_X_rate, highly.methyl.cutoff)
          candidate.highly.methylated.sites.motif <- candidate.highly.methylated.sites.motif[candidate.highly.methylated.sites.motif$treatment_X_rate>=high.cutoff, ]
          N_fixed_treatment_prime <- candidate.highly.methylated.sites.motif$treatment_fixed_count
          N_total_treatment_prime <- candidate.highly.methylated.sites.motif$treatment_depth
          lambda1.motif_seqs.est[i] <- MLE_for_lambda1(N_fixed_treatment_prime, N_total_treatment_prime, delta = delta, initial_lambda1 = 0.2)
      }
    } else if(Nmer == "f4mer") {
      motif_seqs_f4 <- unique(apply(target_motif[, -4], 1, function(x){paste(x, collapse = "")}))
      lambda1.motif_seqs_f4.est <- rep(NA, length(motif_seqs_f4))
      for(i in 1:length(motif_seqs_f4)){
          candidate.highly.methylated.sites.motif <- candidate.highly.methylated.sites[substr(candidate.highly.methylated.sites$motif, 1, 4) %in% motif_seqs_f4[i], ]
          high.cutoff <- quantile(candidate.highly.methylated.sites.motif$treatment_X_rate, highly.methyl.cutoff)
          candidate.highly.methylated.sites.motif <- candidate.highly.methylated.sites.motif[candidate.highly.methylated.sites.motif$treatment_X_rate>=high.cutoff, ]
          N_fixed_treatment_prime <- candidate.highly.methylated.sites.motif$treatment_fixed_count
          N_total_treatment_prime <- candidate.highly.methylated.sites.motif$treatment_depth
          lambda1.motif_seqs_f4.est[i] <- MLE_for_lambda1(N_fixed_treatment_prime, N_total_treatment_prime, delta = delta, initial_lambda1 = 0.2)
      }
      for(i in 1:length(motif_seqs)){
          lambda1.motif_seqs.est[i] <- lambda1.motif_seqs_f4.est[which(motif_seqs_f4%in%substr(motif_seqs[i], 1, 4))]
       }
    } else if(Nmer == "l4mer") {
      motif_seqs_l4 <- unique(apply(target_motif[, -1], 1, function(x){paste(x, collapse = "")}))
      lambda1.motif_seqs_l4.est <- rep(NA, length(motif_seqs_l4))
      for(i in 1:length(motif_seqs_l4)){
          candidate.highly.methylated.sites.motif <- candidate.highly.methylated.sites[substr(candidate.highly.methylated.sites$motif, 2, 5) %in% motif_seqs_l4[i], ]
          high.cutoff <- quantile(candidate.highly.methylated.sites.motif$treatment_X_rate, highly.methyl.cutoff)
          candidate.highly.methylated.sites.motif <- candidate.highly.methylated.sites.motif[candidate.highly.methylated.sites.motif$treatment_X_rate>=high.cutoff, ]
          N_fixed_treatment_prime <- candidate.highly.methylated.sites.motif$treatment_fixed_count
          N_total_treatment_prime <- candidate.highly.methylated.sites.motif$treatment_depth
          lambda1.motif_seqs_l4.est[i] <- MLE_for_lambda1(N_fixed_treatment_prime, N_total_treatment_prime, delta = delta, initial_lambda1 = 0.2)
      }
      for(i in 1:length(motif_seqs)){
          lambda1.motif_seqs.est[i] <- lambda1.motif_seqs_l4.est[which(motif_seqs_l4%in%substr(motif_seqs[i], 2, 5))]
       }
    } else {
      cat("The Nmer option is only one of 5mer, f4mer or l4mer!!!\n")
      q(status = 1)
    }
  } else {

    lambda1.motif_seqs.est <- rep(lambda1.est, length(motif_seqs))

  }

  lambda1.motif_seqs.summary <- data.frame(lambda1 = lambda1.motif_seqs.est, motif = motif_seqs)

  lambda1.non_motif_seqs.est <- lambda1.est

  rest.motif <- motif_ref_types[which(!motif_ref_types%in%motif_seqs)]
  lambda1.non_motif_seqs.summary <- data.frame(lambda1 = numeric(0), motif = character(0))
  if(length(rest.motif) > 0) {
    lambda1.non_motif_seqs.summary <- data.frame(lambda1 = rep(as.numeric(lambda1.non_motif_seqs.est), length(rest.motif)), motif = rest.motif)
  }
  #lambda1.motif_seqs.summary[lambda1.motif_seqs.summary[, 1] < lambda1.est, 1] <- lambda1.est

  lambda1.summary <- rbind(lambda1.motif_seqs.summary, lambda1.non_motif_seqs.summary)
  #if(is.null(ref.freq.tab)){
  #  data(freq.tab)
  #} else {
  #  freq.tab <- ref.freq.tab
  #}

  lambda1.motif.summary <- dplyr::left_join(lambda1.summary, ref.freq.tab, by=c("motif"="motif"))

  ######### Bayesian inference for each site

  ##### Homo
  homosites <- dplyr::left_join(homosites, lambda1.motif.summary[, c("motif", "lambda1", "prior_methylated")], by=c("motif"= "motif"))
  homosites <- homosites[!is.na(homosites$prior_methylated), ]
  if(thread == 1) {
    homo_res <- apply(homosites[, c("treatment_fixed_count", "treatment_depth", "lambda1", "prior_methylated")], 1, function(x){Bayesian_inference_for_beta_homo(x[1], x[2], x[3], lambda2.est, x[4], delta = delta, initial_beta = 0.2)})
  } else {
    cl <- makeCluster(thread, type="FORK")
    registerDoParallel(cl)
    cat(paste("Hyper-thread registered:",getDoParRegistered(),"\n"))
    cat(paste("Using",getDoParWorkers(),"threads to make homo beta estimation...\n"))
    homosites_treatment_fixed_count_split <- split(homosites$treatment_fixed_count, factor(sort(1:length(homosites$treatment_fixed_count)%%thread)))
    homosites_treatment_depth_split <- split(homosites$treatment_depth, factor(sort(1:length(homosites$treatment_depth)%%thread)))
    homosites_lambda1_split <- split(homosites$lambda1, factor(sort(1:length(homosites$lambda1)%%thread)))
    homosites_prior_methylated_split <- split(homosites$prior_methylated, factor(sort(1:length(homosites$prior_methylated)%%thread)))
    homo_res <- foreach(i = 1:thread, .combine = cbind) %dopar% {
      apply(cbind(as.vector(unlist(homosites_treatment_fixed_count_split[i])), as.vector(unlist(homosites_treatment_depth_split[i])), as.vector(unlist(homosites_lambda1_split[i])), as.vector(unlist(homosites_prior_methylated_split[i]))), 1, function(x){Bayesian_inference_for_beta_homo(x[1], x[2], x[3], lambda2.est, x[4], delta = delta, initial_beta = 0.2)})
    }
    stopCluster(cl)
  }
  homosites$beta_est <- homo_res[1, ]
  homosites$posterior <- homo_res[2, ]

 # homosites.hits <- homosites[!is.na(homosites$posterior) & homosites$posterior <= 0.05 & homosites$beta>=0.05, ]

  ##### Heter
  hetersites <- allsites[-homo.ID, ]
  hetersites <- dplyr::left_join(hetersites, lambda1.motif.summary, by=c("motif"="motif"))
  #hetersites <- hetersites[hetersites$control_fixed_rate >= 0.01 & hetersites$treatment_fixed_rate != 1, ]
  if(thread == 1) {
    heter_res <- apply(hetersites[, c("treatment_fixed_count", "treatment_depth", "control_fixed_count", "control_depth", "lambda1", "prior_methylated")], 1, function(x){Bayesian_inference_for_beta_kappa_heter(x[1], x[2], x[3], x[4], x[5], lambda2.est, x[6], delta = delta)})
  } else {
    cl <- makeCluster(thread, type="FORK")
    registerDoParallel(cl)
    cat(paste("Hyper-thread registered:",getDoParRegistered(),"\n"))
    cat(paste("Using",getDoParWorkers(),"threads to make heter beta estimation...\n"))
    hetersites_treatment_fixed_count_split <- split(hetersites$treatment_fixed_count, factor(sort(1:length(hetersites$treatment_fixed_count)%%thread)))
    hetersites_treatment_depth_split <- split(hetersites$treatment_depth, factor(sort(1:length(hetersites$treatment_depth)%%thread)))
    hetersites_control_fixed_count_split <- split(hetersites$control_fixed_count, factor(sort(1:length(hetersites$control_fixed_count)%%thread)))
    hetersites_control_depth_split <- split(hetersites$control_depth, factor(sort(1:length(hetersites$control_depth)%%thread)))
    hetersites_lambda1_split <- split(hetersites$lambda1, factor(sort(1:length(hetersites$lambda1)%%thread)))
    hetersites_prior_methylated_split <- split(hetersites$prior_methylated, factor(sort(1:length(hetersites$prior_methylated)%%thread)))
    heter_res <- foreach(i = 1:thread, .combine = cbind) %dopar% {
      apply(cbind(as.vector(unlist(hetersites_treatment_fixed_count_split[i])), as.vector(unlist(hetersites_treatment_depth_split[i])), as.vector(unlist(hetersites_control_fixed_count_split[i])), as.vector(unlist(hetersites_control_depth_split[i])),as.vector(unlist(hetersites_lambda1_split[i])), as.vector(unlist(hetersites_prior_methylated_split[i]))), 1, function(x){Bayesian_inference_for_beta_kappa_heter(x[1], x[2], x[3], x[4], x[5], lambda2.est, x[6], delta = delta)})
    }
    stopCluster(cl)
  }

  hetersites$kappa_est <- heter_res[1, ]
  hetersites$beta_est <- heter_res[2, ]
  hetersites$posterior <- heter_res[3, ]

# hetersites.hits <- hetersites[hetersites$posterior <= 0.05 & hetersites$beta >= 0.05, ]

  res <- list(homosites = homosites, hetersites = hetersites, lambda1 = lambda1.motif.summary, lambda2 = lambda2.est)

  return(res)

}
