#' Estimate constant on-target mutation rates
#'
#' \code{estimate_inference_with_empirical} assumes a constant on-target mutation or conversion rate for all sites regardless of sequence context, and estimates site-level signal using a maximum-likelihood approach.
#'
#' @param chr.info A \code{data.frame} with three columns: site position in the format "chrom_coordinate_strand" (e.g., chr1_14404_-), site motif sequence (e.g., AAACC), and site motif type (e.g., NNUNN).
#' @param treatment_fixed_count A \code{vector} of non-mutation counts for each site in the treatment sample.
#' @param control_fixed_count A \code{vector} of non-mutation counts for each site in the control sample.
#' @param treatment_depth A \code{vector} of read coverage for each site in the treatment sample.
#' @param control_depth A \code{vector} of read coverage for each site in the control sample.
#' @param delta The sequencing error rate. Default is 0.001.
#' @param depth.cutoff The minimum read coverage for each site in the treatment and control sample. Default is 10.
#' @param homo.cutoff The minimum ratio of non-mutation counts for each site in the control sample that is used to determine homozygous sites. Default is 0.99.
#' @param lambda1 The method to estimate the on-target mutation rate. One of "auto", "site" or a numeric value between 0 and 1.
#' If "auto", the on-target mutation rate is estimated from the upper quantile of candidate signal sites, where the quantile is defined by \code{highly.methyl.cutoff}.
#' If "site", the on-target mutation rate is estimated based on a user-defined site set that is provided by the argument \code{top.sites}.
#' If a numeric value between 0 and 1, the on-target mutation rate is explicitly defined as the value. Default is "auto".
#' @param top.sites A site set used to estimate the on-target rate. One line or vector element should correspond to one site ID. The argument is only used if \code{lambda1 = "site"}.
#' @param bg.method The statistical test to infer the background sites. One of "binomial", "fisher", "lrt". Default is "fisher".
#' @param bg.target A \code{string} indicating what type of read count data used to estimate the background mutation rate. One of "treatment", "control" or "both".
#' If "treatment", uses the read count data from the treatment sample; if "control", from the control sample; if "both", from both. Default is "treatment".
#' @param highly.methyl.cutoff The upper quantile cutoff of candidate signal sites used for estimating the on-target mutation rate. This argument name is retained for backward compatibility. Default is 0.95.
#' @param seed A seed for the random number generators.
#' @param thread A positive integer numeric specifying the number of cores for parallel computing. Default is 1.
#'
#' @return A \code{list} including a \code{data.frame} of homozygous sites, a \code{data.frame} of heterozygous sites, the estimated on-target mutation rate (lambda1), and the estimated background mutation rate (lambda2).
#'
#' @details \code{estimate_inference_with_empirical} takes a site-level count table as input. The table can be generated by any preprocessing pipeline as long as it contains site IDs, motif annotations, treatment and control fixed-base counts, and treatment and control read depths in the expected order.
#' If one would like to estimate the on-target mutation rate using a user-defined site set, an extra site set is required. See the argument \code{top.sites} for details.
#'
#' @examples
#' # Estimate signal levels from a PAR-CLIP count table.
#' count_table <- read.delim(system.file("extdata", "pos.read.count.example.parclip.txt",
#'                                       package = "MIRAGE"))
#' res <- with(count_table, estimate_inference_with_empirical(cbind(pos, motif, type),
#'             treated_fixed_count, control_fixed_count, treated_depth, control_depth,
#'             delta = 0.001, depth.cutoff = 10, lambda1 = "auto", top.sites = NULL,
#'             bg.method = "lrt", bg.target = "both", highly.methyl.cutoff = 0.95,
#'             seed = 123, thread = 1))
#' head(res$homosites[, c("pos", "motif", "beta_est", "lrt_fdr")])
#'
#' @export

estimate_inference_with_empirical <- function(chr.info, treatment_fixed_count, control_fixed_count, treatment_depth, control_depth, delta = 0.001, depth.cutoff = 10, homo.cutoff = 0.99, lambda1 = "auto", top.sites=NULL, bg.method = "fisher", bg.target = "treatment", highly.methyl.cutoff = 0.95, seed = NULL, thread = 1){



  treatment_fixed_rate <- treatment_fixed_count/treatment_depth
  control_fixed_rate <- control_fixed_count/control_depth

  treatment_X_rate <- 1 - treatment_fixed_rate
  control_X_rate <- 1 - control_fixed_rate

  allsites <- data.frame(chr.info,  treatment_X_rate, control_X_rate, treatment_fixed_rate, control_fixed_rate, treatment_fixed_count, control_fixed_count, treatment_depth, control_depth)
  allsites <- allsites[allsites$treatment_depth >= depth.cutoff & allsites$control_depth >= depth.cutoff, ]

  ####### Select homozygous sites based on the AF #######
  homo.ID <- which(allsites$control_fixed_rate > homo.cutoff)
  homosites <- allsites[homo.ID, ]
  homosites_percentage <- round(nrow(homosites)/nrow(allsites)*100,2)
  cat(paste0("Considering ",nrow(homosites)," (",homosites_percentage,"%) sites as homozygous...\n"))
  background.cutoff <- quantile(homosites$treatment_X_rate, 0.95)
  initial_background_rate <- median(homosites$treatment_X_rate[homosites$treatment_X_rate <= background.cutoff])

  if(thread == 1) {
    homosites.initial.test.summary <- test_for_mutation_given_a_rate(homosites$treatment_fixed_count, homosites$treatment_depth, homosites$control_fixed_count, homosites$control_depth, initial_background_rate)
  } else {
    cl <- makeCluster(thread, type="FORK")
    registerDoParallel(cl)
    cat(paste("Hyper-thread registered:",getDoParRegistered(),"\n"))
    cat(paste("Using",getDoParWorkers(),"threads to make homo initial test...\n"))
    homosites_treatment_fixed_count_split <- split(homosites$treatment_fixed_count, factor(sort(1:length(homosites$treatment_fixed_count)%%thread)))
    homosites_treatment_depth_split <- split(homosites$treatment_depth, factor(sort(1:length(homosites$treatment_depth)%%thread)))
    homosites_control_fixed_count_split <- split(homosites$control_fixed_count, factor(sort(1:length(homosites$control_fixed_count)%%thread)))
    homosites_control_depth_split <- split(homosites$control_depth, factor(sort(1:length(homosites$control_depth)%%thread)))
    homosites.initial.test.summary <- foreach(i = 1:thread, .combine = rbind) %dopar% {
      test_for_mutation_given_a_rate(as.vector(unlist(homosites_treatment_fixed_count_split[i])), as.vector(unlist(homosites_treatment_depth_split[i])), as.vector(unlist(homosites_control_fixed_count_split[i])), as.vector(unlist(homosites_control_depth_split[i])), initial_background_rate)
    }
    stopCluster(cl)
  }

  ####### Estimate mutation rate in background #######
  if(bg.method == "binomial") {
    Igroup0 <- which(homosites.initial.test.summary$binom_p > 0.05)
    Igroup1 <- which(homosites.initial.test.summary$binom_fdr < 0.05)
  } else if(bg.method == "fisher") {
    Igroup0 <- which(homosites.initial.test.summary$fisher_p > 0.05)
    Igroup1 <- which(homosites.initial.test.summary$fisher_fdr < 0.05)
  } else if(bg.method == "lrt") {
    Igroup0 <- which(homosites.initial.test.summary$lrt_p > 0.05)
    Igroup1 <- which(homosites.initial.test.summary$lrt_fdr < 0.05)
  } else {
    cat("The bg.method option is only one of binomial, fisher or lrt!!!\n")
    q(status = 1)
  }
  #Igroup0 <- which(homosites.initial.test.summary$binom_p > 0.05)
  candidate.background.sites <- homosites[Igroup0, ]
  candidate.background.sites.percentage <- round(nrow(candidate.background.sites)/nrow(homosites)*100,2)
  cat(paste0("Considering ",nrow(candidate.background.sites)," (",candidate.background.sites.percentage,"%) sites as background (homozygous sites only)...\n"))
  if(bg.target == "treatment") {
    N_fixed_bg <- candidate.background.sites$treatment_fixed_count
    N_total_bg <- candidate.background.sites$treatment_depth
  } else if(bg.target == "control") {
    N_fixed_bg <- candidate.background.sites$control_fixed_count
    N_total_bg <- candidate.background.sites$control_depth
  } else if(bg.target == "both") {
    N_fixed_bg <- c(candidate.background.sites$treatment_fixed_count,candidate.background.sites$control_fixed_count)
    N_total_bg <- c(candidate.background.sites$treatment_depth,candidate.background.sites$control_depth)
  } else {
    cat("The bg.target option is only one of treatment, control or both!!!\n")
    q(status = 1)
  }

  lambda2.est <- MLE_for_lambda2(N_fixed_bg, N_total_bg, num.sites = 100000, delta = delta, initial_lambda2 = 0.1, seed = seed)

  final.background.rate <- lambda2.est*(1-delta/3) + (1-lambda2.est)*delta

  if(thread == 1) {
    homosites.final.test.summary <- test_for_mutation_given_a_rate(homosites$treatment_fixed_count, homosites$treatment_depth, homosites$control_fixed_count, homosites$control_depth, final.background.rate)
  } else {
    cl <- makeCluster(thread, type="FORK")
    registerDoParallel(cl)
    cat(paste("Hyper-thread registered:",getDoParRegistered(),"\n"))
    cat(paste("Using",getDoParWorkers(),"threads to make homo final test...\n"))
    homosites.final.test.summary <- foreach(i = 1:thread, .combine = rbind) %dopar% {
      test_for_mutation_given_a_rate(as.vector(unlist(homosites_treatment_fixed_count_split[i])), as.vector(unlist(homosites_treatment_depth_split[i])), as.vector(unlist(homosites_control_fixed_count_split[i])), as.vector(unlist(homosites_control_depth_split[i])), final.background.rate)
    }
    stopCluster(cl)
  }
  homosites$binom_p <- homosites.final.test.summary$binom_p
  homosites$binom_fdr <- homosites.final.test.summary$binom_fdr
  homosites$fisher_p <- homosites.final.test.summary$fisher_p
  homosites$fisher_fdr <- homosites.final.test.summary$fisher_fdr
  homosites$log_lik_ratio <- homosites.final.test.summary$lrt
  homosites$lrt_p <- homosites.final.test.summary$lrt_p
  homosites$lrt_fdr <- homosites.final.test.summary$lrt_fdr

  ####### Estimate mutation rate in high-signal sites #######
  #Igroup1 <- which(homosites.initial.test.summary$fisher_fdr < 0.05)
  if(lambda1 == "auto") {
    candidate.highly.methylated.sites <- homosites[Igroup1, ]
    candidate.highly.methylated.sites.percentage <- round(nrow(candidate.highly.methylated.sites)/nrow(homosites)*100,2)
    cat(paste0("Considering ",nrow(candidate.highly.methylated.sites)," (",candidate.highly.methylated.sites.percentage,"%) sites as high-signal site candidates (homozygous sites only)...\n"))
    high.cutoff <- quantile(candidate.highly.methylated.sites$treatment_X_rate, highly.methyl.cutoff)
    candidate.highly.methylated.sites.filter <- candidate.highly.methylated.sites[candidate.highly.methylated.sites$treatment_X_rate>=high.cutoff, ]
    N_fixed_treatment_prime <- candidate.highly.methylated.sites.filter$treatment_fixed_count
    N_total_treatment_prime <- candidate.highly.methylated.sites.filter$treatment_depth
    lambda1.est <- MLE_for_lambda1(N_fixed_treatment_prime, N_total_treatment_prime, delta = delta, initial_lambda1 = 0.2)
  } else if(lambda1 == "site") {
    if(is.null(top.sites)) {
      cat("When the value of lambda1 is 'site', a set of top sites are needed as input to top.sites!!!\n")
      q(status = 1)
    } else {
      candidate.highly.methylated.sites.filter <- allsites[allsites$pos %in% top.sites,]
      cat(paste0("Considering ",nrow(candidate.highly.methylated.sites.filter)," sites as high-signal site candidates...\n"))
      N_fixed_treatment_prime <- candidate.highly.methylated.sites.filter$treatment_fixed_count
      N_total_treatment_prime <- candidate.highly.methylated.sites.filter$treatment_depth
      lambda1.est <- MLE_for_lambda1(N_fixed_treatment_prime, N_total_treatment_prime, delta = delta, initial_lambda1 = 0.2)
    }
  } else {
    lambda1.est <- lambda1
  }

  ####### Estimate site-specific signal for homozygous sites #######
  if(thread == 1) {
    homo_beta_est <- apply(homosites[, c("treatment_fixed_count", "treatment_depth")], 1, function(x){MLE_for_beta_homo(x[1], x[2], lambda1.est, lambda2.est, delta = delta, initial_beta = 0.2)})
  } else {
    cl <- makeCluster(thread, type="FORK")
    registerDoParallel(cl)
    cat(paste("Hyper-thread registered:",getDoParRegistered(),"\n"))
    cat(paste("Using",getDoParWorkers(),"threads to make homo beta estimation...\n"))
    homo_beta_est <- foreach(i = 1:thread, .combine = 'c') %dopar% {
      apply(cbind(as.vector(unlist(homosites_treatment_fixed_count_split[i])), as.vector(unlist(homosites_treatment_depth_split[i]))), 1, function(x){MLE_for_beta_homo(x[1], x[2], lambda1.est, lambda2.est, delta = delta, initial_beta = 0.2)})
    }
    stopCluster(cl)
  }
  homosites$beta_est <- homo_beta_est


  ####### Estimate site-specific signal for heterozygous sites #######
  hetersites <- allsites[-homo.ID, ]
  if(thread == 1) {
    heter_beta_est <- apply(hetersites[, c("treatment_fixed_count", "treatment_depth", "control_fixed_count", "control_depth")], 1, function(x){MLE_joint_for_beta_kappa_heter(x[1], x[2], x[3], x[4], lambda1.est, lambda2.est, delta = delta, initial_beta = 0.2, initial_kappa = 0.5)})
    hetersites$beta_est <- heter_beta_est[1, ]
    hetersites$kappa_est <- heter_beta_est[2, ]
    heter.background.rate <- (1-hetersites$kappa_est)*(1-delta/3) + hetersites$kappa_est*(lambda2.est*(1-delta/3) + (1-lambda2.est)*delta)
    hetersites.test.summary <- apply(cbind(hetersites[, c("treatment_fixed_count", "treatment_depth", "control_fixed_count", "control_depth")], heter.background.rate), 1, function(x){test_for_mutation_given_a_rate(x[1], x[2], x[3], x[4], x[5])})
    hetersites.test.summary <- do.call(rbind,lapply(hetersites.test.summary,data.frame))
    hetersites$binom_p <- hetersites.test.summary$binom_p
    hetersites$binom_fdr <- p.adjust(hetersites$binom_p, method="BH")
    hetersites$fisher_p <- hetersites.test.summary$fisher_p
    hetersites$fisher_fdr <- p.adjust(hetersites$fisher_p, method="BH")
    hetersites$log_lik_ratio <- hetersites.test.summary$lrt
    hetersites$lrt_p <- hetersites.test.summary$lrt_p
    hetersites$lrt_fdr <- p.adjust(hetersites$lrt_p, method="BH")
  } else {
    cl <- makeCluster(thread, type="FORK")
    registerDoParallel(cl)
    cat(paste("Hyper-thread registered:",getDoParRegistered(),"\n"))
    cat(paste("Using",getDoParWorkers(),"threads to make heter beta estimation...\n"))
    hetersites_treatment_fixed_count_split <- split(hetersites$treatment_fixed_count, factor(sort(1:length(hetersites$treatment_fixed_count)%%thread)))
    hetersites_treatment_depth_split <- split(hetersites$treatment_depth, factor(sort(1:length(hetersites$treatment_depth)%%thread)))
    hetersites_control_fixed_count_split <- split(hetersites$control_fixed_count, factor(sort(1:length(hetersites$control_fixed_count)%%thread)))
    hetersites_control_depth_split <- split(hetersites$control_depth, factor(sort(1:length(hetersites$control_depth)%%thread)))
    heter_beta_est <- foreach(i = 1:thread, .combine = cbind) %dopar% {
      apply(cbind(as.vector(unlist(hetersites_treatment_fixed_count_split[i])), as.vector(unlist(hetersites_treatment_depth_split[i])), as.vector(unlist(hetersites_control_fixed_count_split[i])), as.vector(unlist(hetersites_control_depth_split[i]))), 1, function(x){MLE_joint_for_beta_kappa_heter(x[1], x[2], x[3], x[4], lambda1.est, lambda2.est, delta = delta, initial_beta = 0.2, initial_kappa = 0.5)})
    }
    hetersites$beta_est <- heter_beta_est[1, ]
    hetersites$kappa_est <- heter_beta_est[2, ]
    heter.background.rate <- (1-hetersites$kappa_est)*(1-delta/3) + hetersites$kappa_est*(lambda2.est*(1-delta/3) + (1-lambda2.est)*delta)
    heter.background.rate.split <- split(heter.background.rate, factor(sort(1:length(heter.background.rate)%%thread)))
    hetersites.test.summary <- foreach(i = 1:thread, .combine = rbind) %dopar% {
      do.call(rbind, lapply(apply(cbind(as.vector(unlist(hetersites_treatment_fixed_count_split[i])), as.vector(unlist(hetersites_treatment_depth_split[i])), as.vector(unlist(hetersites_control_fixed_count_split[i])), as.vector(unlist(hetersites_control_depth_split[i])), as.vector(unlist(heter.background.rate.split[i]))), 1, function(x){test_for_mutation_given_a_rate(x[1], x[2], x[3], x[4], x[5])}),data.frame))
    }
    hetersites$binom_p <- hetersites.test.summary$binom_p
    hetersites$binom_fdr <- p.adjust(hetersites$binom_p, method="BH")
    hetersites$fisher_p <- hetersites.test.summary$fisher_p
    hetersites$fisher_fdr <- p.adjust(hetersites$fisher_p, method="BH")
    hetersites$log_lik_ratio <- hetersites.test.summary$lrt
    hetersites$lrt_p <- hetersites.test.summary$lrt_p
    hetersites$lrt_fdr <- p.adjust(hetersites$lrt_p, method="BH")
    stopCluster(cl)
  }

  res <- list(homosites = homosites, hetersites = hetersites, lambda1 = lambda1.est, lambda2 = lambda2.est)

  return(res)
}
